### ISSUE TITLE
deposit  eth error

### ISSUE THREAD

**Issue by liuguangbanzang** [zksync-sdk/zksync2-java#21]
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.web3j.abi.datatypes.DynamicArray.getTypeAsString(DynamicArray.java:69)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.web3j.abi.FunctionEncoder.buildMethodSignature(FunctionEncoder.java:83)
	at io.zksync.abi.ZkFunctionEncoder.encodeFunction(ZkFunctionEncoder.java:33)
	at org.web3j.abi.FunctionEncoder.encode(FunctionEncoder.java:46)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:344)
	at org.web3j.tx.Contract.lambda$executeRemoteCallTransaction$4(Contract.java:415)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:42)
	at org.web3j.utils.Async.lambda$run$1(Async.java:38)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by liuguangbanzang** [comment]
I updated the latest web3j SDK and I don't have this error
