### ISSUE TITLE
Revert reason: 'execution reverted'.

### ISSUE THREAD

**Issue by liu-a111** [zksync-sdk/zksync2-java#45]
#### 📝 Description

Hello, Sir. I have deployed a Contract to the era_node_test network. Using zysync2-java, I am able to call view methods within the Contract, but I am unable to invoke methods that consume gas.

#### 🖥️ Environment

- **Operating System & Version**: [e.g., Ubuntu 22.04]
- **Other relevant environment details**: zksync-java0.3.0 

#### 📋 Additional Context
` 
17:28:02.420 [main] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","error":{"code":3,"message":"execution reverted","data":"0x"},"id":9}

17:28:02.420 [main] DEBUG org.web3j.protocol.http.HttpService - <-- END HTTP (87-byte body)
Exception in thread "main" org.web3j.protocol.exceptions.TransactionException: Transaction 0x4f22aee9d0e477914df3b4ab81a2b963c739d27e289df805fbf5bb7e2d3453ed has failed with status: 0x0. Gas used: 130610. Revert reason: 'execution reverted'.
        at org.web3j.tx.Contract.executeTransaction(Contract.java:435)
        at org.web3j.tx.Contract.executeTransaction(Contract.java:374)
        at org.web3j.tx.Contract.executeTransaction(Contract.java:368)
        at org.web3j.tx.Contract.executeTransaction(Contract.java:363)
        at org.web3j.tx.Contract.lambda$executeRemoteCallTransaction$3(Contract.java:468)
        at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:42)
        at Main.main(Main.java:61)
`

**Comment by petarTxFusion** [comment]
Can you maybe share how you call that contract? I assume that this could be a solution for your problem, you should build call data using `ZkFunctionEncoder`
```
final Function function = new Function(
                FUNC_FINALIZEWITHDRAWAL,
                Arrays.<Type>asList(new Uint256(_chainId),
                        new Uint256(_l2BatchNumber),
                        new Uint256(_l2MessageIndex),
                        new org.web3j.abi.datatypes.generated.Uint16(_l2TxNumberInBatch),
                        new DynamicBytes(_message),
                        new DynamicArray<Bytes32>(
                                Bytes32.class,
                                org.web3j.abi.Utils.typeMap(_merkleProof, Bytes32.class))),
                Collections.<TypeReference<?>>emptyList());
        return ZkFunctionEncoder.encode(function);

**Comment by liu-a111** [comment]
> Can you maybe share how you call that contract? I assume that this could be a solution for your problem, you should build call data using `ZkFunctionEncoder`
> 
> ```
> final Function function = new Function(
>                 FUNC_FINALIZEWITHDRAWAL,
>                 Arrays.<Type>asList(new Uint256(_chainId),
>                         new Uint256(_l2BatchNumber),
>                         new Uint256(_l2MessageIndex),
>                         new org.web3j.abi.datatypes.generated.Uint16(_l2TxNumberInBatch),
>                         new DynamicBytes(_message),
>                         new DynamicArray<Bytes32>(
>                                 Bytes32.class,
>                                 org.web3j.abi.Utils.typeMap(_merkleProof, Bytes32.class))),
>                 Collections.<TypeReference<?>>emptyList());
>         return ZkFunctionEncoder.encode(function);
> ```

Hello, Sir. I invoke the Contract through the following method.Thank you,sir.
`
        EthSigner signer = new PrivateKeyEthSigner(credentials, 260L);
        ZkTransactionFeeProvider feeProvider = new DefaultTransactionFeeProvider(zksync,Token.ETH);
        ZkSyncTransactionManager transactionManager = new ZkSyncTransactionManager(zksync, signer, feeProvider);
        Test t = Test.load(contract_address, zksync, transactionManager, new DefaultGasProvider());
        TransactionReceipt receipt = t.setA(BigInteger.ONE).send();
        System.out.println(receipt.getRevertReason());
`

**Comment by petarTxFusion** [comment]
Can you please try to encode it using `ZkFuntionEncoder` and not one from the `web3j`

**Comment by liu-a111** [comment]
> Can you please try to encode it using `ZkFuntionEncoder` and not one from the `web3j`

Sir, alright, I will give it a try immediately.

**Comment by liu-a111** [comment]
> Can you please try to encode it using `ZkFuntionEncoder` and not one from the `web3j`

hi,sir I try as below ,but the issue still exists.
`       List res = new ArrayList();
        String contract_address="0x588758d8a0ad1162a6294f3c274753137e664ae0";
        Function contractFunction = new Function(
                "setA",
                 Arrays.<Type>asList(new Uint256(123)),
                 Collections.<TypeReference<?>>emptyList());
        String calldata = ZkFunctionEncoder.encode(contractFunction);
        TransactionReceipt receipt2 = wallet.execute(contract_address, contractFunction).send();
        `
      the sol file is as below
      `
      pragma solidity ^0.8.0;
contract Test{
    int a ;
    function setA(int b) public {
        int c = b;
    }
    function get() public view returns  (int) {
        return a;
    }
}
      `

**Comment by liu-a111** [comment]
> Can you please try to encode it using `ZkFuntionEncoder` and not one from the `web3j`

Sir ,I can call function by ` npx zksync-cli contract write --rpc http://127.0.0.1:8011 ` , but it doesn't work with ZKSync 2-java sdk.

**Comment by petarTxFusion** [comment]
Here is simple example with storage contract you can try it. If you continue to have problems maybe you can share me your contract, abi and bin.
```
String bin = "0x0002000000000002000100000001035500000000030100190000006003300270000000130030019d0000008004000039000000400040043f00000013033001970000000102200190000000290000c13d000000040230008c000000420000413d000000000101043b000000e001100270000000150210009c000000310000613d000000160110009c000000420000c13d0000000001000416000000000101004b000000420000c13d000000040100008a00000000011000310000001702000041000000200310008c000000000300001900000000030240190000001701100197000000000401004b000000000200a019000000170110009c00000000010300190000000001026019000000000101004b000000420000c13d00000004010000390000000101100367000000000101043b000000000010041b0000000001000019000000490001042e0000000001000416000000000101004b000000420000c13d0000002001000039000001000010044300000120000004430000001401000041000000490001042e0000000001000416000000000101004b000000420000c13d000000040100008a00000000011000310000001702000041000000000301004b000000000300001900000000030240190000001701100197000000000401004b000000000200a019000000170110009c00000000010300190000000001026019000000000101004b000000440000613d00000000010000190000004a00010430000000000100041a000000800010043f0000001801000041000000490001042e0000004800000432000000490001042e0000004a00010430000000000000000000000000000000000000000000000000000000000000000000000000ffffffff0000000200000000000000000000000000000040000001000000000000000000000000000000000000000000000000000000000000000000000000006d4ce63c0000000000000000000000000000000000000000000000000000000060fe47b1800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000008000000000000000000000000000000000000000000000000000000000000000000000000000000000e69512c94890ba2a8ca933413f57834c632dc3539b4ce6d968c0185b902f8025";
TransactionReceipt result = wallet.deploy(Numeric.hexStringToByteArray(bin)).sendAsync().join();
System.out.println("Contract address: " + result.getContractAddress());

Function increment = new Function("set", Arrays.<Type>asList(new org.web3j.abi.datatypes.generated.Uint256(100)),
                Collections.<TypeReference<?>>emptyList());
wallet.execute(result.getContractAddress(), increment).sendAsync().join();

**Comment by liu-a111** [comment]
> Here is simple example with storage contract you can try it. If you continue to have problems maybe you can share me your contract, abi and bin.
> 
> ```
> String bin = "0x0002000000000002000100000001035500000000030100190000006003300270000000130030019d0000008004000039000000400040043f00000013033001970000000102200190000000290000c13d000000040230008c000000420000413d000000000101043b000000e001100270000000150210009c000000310000613d000000160110009c000000420000c13d0000000001000416000000000101004b000000420000c13d000000040100008a00000000011000310000001702000041000000200310008c000000000300001900000000030240190000001701100197000000000401004b000000000200a019000000170110009c00000000010300190000000001026019000000000101004b000000420000c13d00000004010000390000000101100367000000000101043b000000000010041b0000000001000019000000490001042e0000000001000416000000000101004b000000420000c13d0000002001000039000001000010044300000120000004430000001401000041000000490001042e0000000001000416000000000101004b000000420000c13d000000040100008a00000000011000310000001702000041000000000301004b000000000300001900000000030240190000001701100197000000000401004b000000000200a019000000170110009c00000000010300190000000001026019000000000101004b000000440000613d00000000010000190000004a00010430000000000100041a000000800010043f0000001801000041000000490001042e0000004800000432000000490001042e0000004a00010430000000000000000000000000000000000000000000000000000000000000000000000000ffffffff0000000200000000000000000000000000000040000001000000000000000000000000000000000000000000000000000000000000000000000000006d4ce63c0000000000000000000000000000000000000000000000000000000060fe47b1800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000008000000000000000000000000000000000000000000000000000000000000000000000000000000000e69512c94890ba2a8ca933413f57834c632dc3539b4ce6d968c0185b902f8025";
> TransactionReceipt result = wallet.deploy(Numeric.hexStringToByteArray(bin)).sendAsync().join();
> System.out.println("Contract address: " + result.getContractAddress());
> 
> Function increment = new Function("set", Arrays.<Type>asList(new org.web3j.abi.datatypes.generated.Uint256(100)),
>                 Collections.<TypeReference<?>>emptyList());
> wallet.execute(result.getContractAddress(), increment).sendAsync().join();
> ```

Thank you, sir, I feel fortunate to receive your help

**Comment by petarTxFusion** [comment]
No problem, I hope we can resolve this issue you are experiencing

**Comment by liu-a111** [comment]
> No problem, I hope we can resolve this issue you are experiencing

sir,How can I go about obtaining the var  'bin' , for example using  solidity remix  , and the example you provided me is runnable.

**Comment by liu-a111** [comment]
> No problem, I hope we can resolve this issue you are experiencing

sir, How would I compile the sol file to get the correct bin, I think the bin I got when I compiled sol might not be correct

**Comment by liu-a111** [comment]
> > No problem, I hope we can resolve this issue you are experiencing
> 
> sir, How would I compile the sol file to get the correct bin, I think the bin I got when I compiled sol might not be correct

I get the bin by  `zksolc-linux-amd64-gnu-v1.5.8 --solc solc-linux-amd64-0.8.28-1.0.1 --bin Test.sol`

**Comment by liu-a111** [comment]
> No problem, I hope we can resolve this issue you are experiencing
Sir, could you please tell me how to compile the sol file to get its corresponding bin? Does bin refer to bytecode? Thank you, sir.

**Comment by liu-a111** [comment]
my sol file is as below
`// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;
contract Test{
    int a ;
    function set(int b) public {
        a = b;
    }
    function get() public view returns  (int) {
        return a;
    }
}`
bin is
` 
 String bin = "0x0000008003000039000000400030043f0000000100200190000000180000c13d00000060021002700000000c02200197000000040020008c000000250000413d000000000301043b000000e0033002700000000e0030009c000000200000613d0000000f0030009c000000250000c13d0000000003000416000000000003004b000000250000c13d000000230020008c000000250000a13d0000000401100370000000000101043b000000000010041b00000000010000190000002c0001042e0000000001000416000000000001004b000000250000c13d0000002001000039000001000010044300000120000004430000000d010000410000002c0001042e0000000001000416000000000001004b000000250000c13d000000030020008c000000270000213d00000000010000190000002d00010430000000000100041a000000800010043f00000010010000410000002c0001042e0000002b000004320000002c0001042e0000002d000104300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff0000000200000000000000000000000000000040000001000000000000000000000000000000000000000000000000000000000000000000000000006d4ce63c00000000000000000000000000000000000000000000000000000000e5c19b2d00000000000000000000000000000000000000200000008000000000000000000000000000000000000000000000000000000000000000000000000000000000a68fd5f5e675cd0b548395e3a018f8b8cc0d64b57f9339261ad91efb6af4bb45"`
